server:
  port: 9192

spring:
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

  application:
    name: ORDER-SERVICE

logging:
  file:
    name: C:/Users/Mossab/Desktop/log/microservice.log